language: c

services:
  - docker

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

install:
  - make

script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - make build


deploy:
  provider: script
  script: make deploy
  on:
    branch: master


branch: master